export const pokemonNames = [
    "Abomasnow",
    "Abra",
    "Absol",
    "Accelgor",
    "Aegislash",
    "Aerodactyl",
    "Aggron",
    "Aipom",
    "Alakazam",
    "Alcremie",
    "Alomomola",
    "Altaria",
    "Amaura",
    "Ambipom",
    "Amoonguss",
    "Ampharos",
    "Annihilape",
    "Anorith",
    "Appletun",
    "Applin",
    "Araquanid",
    "Arbok",
    "Arboliva",
    "Arcanine",
    "Arceus",
    "Archen",
    "Archeops",
    "Arctibax",
    "Arctovish",
    "Arctozolt",
    "Ariados",
    "Armaldo",
    "Armarouge",
    "Aromatisse",
    "Aron",
    "Arrokuda",
    "Articuno",
    "Audino",
    "Aurorus",
    "Avalugg",
    "Axew",
    "Azelf",
    "Azumarill",
    "Azurill",
    "Bagon",
    "Baltoy",
    "Banette",
    "Barbaracle",
    "Barboach",
    "Barraskewda",
    "Basculegion",
    "Basculin",
    "Bastiodon",
    "Baxcalibur",
    "Bayleef",
    "Beartic",
    "Beautifly",
    "Beedrill",
    "Beheeyem",
    "Beldum",
    "Bellibolt",
    "Bellossom",
    "Bellsprout",
    "Bergmite",
    "Bewear",
    "Bibarel",
    "Bidoof",
    "Binacle",
    "Bisharp",
    "Blacephalon",
    "Blastoise",
    "Blaziken",
    "Blipbug",
    "Blissey",
    "Blitzle",
    "Boldore",
    "Boltund",
    "Bombirdier",
    "Bonsly",
    "Bouffalant",
    "Bounsweet",
    "Braixen",
    "Brambleghast",
    "Bramblin",
    "Braviary",
    "Breloom",
    "Brionne",
    "Bronzong",
    "Bronzor",
    "Brute Bonnet",
    "Bruxish",
    "Budew",
    "Buizel",
    "Bulbasaur",
    "Buneary",
    "Bunnelby",
    "Burmy",
    "Butterfree",
    "Buzzwole",
    "Cacnea",
    "Cacturne",
    "Calyrex",
    "Camerupt",
    "Capsakid",
    "Carbink",
    "Carkol",
    "Carnivine",
    "Carracosta",
    "Carvanha",
    "Cascoon",
    "Castform",
    "Caterpie",
    "Celebi",
    "Celesteela",
    "Centiskorch",
    "Ceruledge",
    "Cetitan",
    "Cetoddle",
    "Chandelure",
    "Chansey",
    "Charcadet",
    "Charizard",
    "Charjabug",
    "Charmander",
    "Charmeleon",
    "Chatot",
    "Cherrim",
    "Cherubi",
    "Chesnaught",
    "Chespin",
    "Chewtle",
    "Chi-Yu",
    "Chien-Pao",
    "Chikorita",
    "Chimchar",
    "Chimecho",
    "Chinchou",
    "Chingling",
    "Ciccino",
    "Cinderace",
    "Clamperl",
    "Clauncher",
    "Clawitzer",
    "Claydol",
    "Clefable",
    "Clefairy",
    "Cleffa",
    "Clobbopus",
    "Clodsire",
    "Cloyster",
    "Coalossal",
    "Cobalion",
    "Cofagrigus",
    "Combee",
    "Combusken",
    "Comfey",
    "Conkeldurr",
    "Copperajah",
    "Corphish",
    "Corsola",
    "Corviknight",
    "Corvisquire",
    "Cosmoem",
    "Cosmog",
    "Cottonee",
    "Crabominable",
    "Crabrawler",
    "Cradily",
    "Cramorant",
    "Cranidos",
    "Crawdaunt",
    "Cresselia",
    "Croagunk",
    "Crobat",
    "Crocalor",
    "Croconaw",
    "Crustle",
    "Cryogonal",
    "Cubchoo",
    "Cubone",
    "Cufant",
    "Cursola",
    "Cutiefly",
    "Cyclizar",
    "Cyndaquil",
    "Dachsbun",
    "Darkrai",
    "Darmanitan",
    "Dartrix",
    "Darumaka",
    "Decidueye",
    "Dedenne",
    "Deerling",
    "Deino",
    "Delcatty",
    "Delibird",
    "Delphox",
    "Deoxys",
    "Dewgong",
    "Dewott",
    "Dewpider",
    "Dhelmise",
    "Dialga",
    "Diancie",
    "Diggersby",
    "Diglett",
    "Ditto",
    "Dodrio",
    "Doduo",
    "Dolliv",
    "Dondozo",
    "Donphan",
    "Dottler",
    "Doublade",
    "Dracovish",
    "Dracozolt",
    "Dragalge",
    "Dragapult",
    "Dragonair",
    "Dragonite",
    "Drakloak",
    "Drampa",
    "Drapion",
    "Dratini",
    "Drednaw",
    "Dreepy",
    "Drifblim",
    "Drifloon",
    "Drilbur",
    "Drizzile",
    "Drowzee",
    "Druddigon",
    "Dubwool",
    "Ducklett",
    "Dudunsparce",
    "Dugtrio",
    "Dunsparce",
    "Duosion",
    "Duraludon",
    "Durant",
    "Dusclops",
    "Dusknoir",
    "Duskull",
    "Dustox",
    "Dwebble",
    "Eelektrik",
    "Eelektross",
    "Eevee",
    "Eiscue",
    "Ekans",
    "Eldegoss",
    "Electabuzz",
    "Electivire",
    "Electrike",
    "Electrode",
    "Elekid",
    "Elgyem",
    "Emboar",
    "Emolga",
    "Empoleon",
    "Enamorus",
    "Entei",
    "Escavalier",
    "Espathra",
    "Espeon",
    "Espurr",
    "Eternatus",
    "Excadrill",
    "Exeggcute",
    "Exeggutor",
    "Exploud",
    "Falinks",
    "Farfetch'd",
    "Farigiraf",
    "Fearow",
    "Feebas",
    "Fennekin",
    "Feraligatr",
    "Ferroseed",
    "Ferrothorn",
    "Fidough",
    "Finizen",
    "Finneon",
    "Flaaffy",
    "Flabébé",
    "Flamigo",
    "Flapple",
    "Flareon",
    "Fletchinder",
    "Fletchling",
    "Flittle",
    "Floatzel",
    "Floette",
    "Floragato",
    "Florges",
    "Flutter Mane",
    "Flygon",
    "Fomantis",
    "Foongus",
    "Forretress",
    "Fraxure",
    "Frigibax",
    "Frillish",
    "Froakie",
    "Frogadier",
    "Froslass",
    "Frosmoth",
    "Fuecoco",
    "Furfrou",
    "Furret",
    "Gabite",
    "Gallade",
    "Galvantula",
    "Garbodor",
    "Garchomp",
    "Gardevoir",
    "Garganacl",
    "Gastly",
    "Gastrodon",
    "Genesect",
    "Gengar",
    "Geodude",
    "Gholdengo",
    "Gible",
    "Gigalith",
    "Gimmighoul",
    "Girafarig",
    "Giratina",
    "Glaceon",
    "Glalie",
    "Glameow",
    "Glastrier",
    "Gligar",
    "Glimmet",
    "Glimmora",
    "Gliscor",
    "Gloom",
    "Gogoat",
    "Golbat",
    "Goldeen",
    "Golduck",
    "Golem",
    "Golett",
    "Golisopod",
    "Golurk",
    "Goodra",
    "Goomy",
    "Gorebyss",
    "Gossifleur",
    "Gothita",
    "Gothitelle",
    "Gothorita",
    "Gourgeist",
    "Grafaiai",
    "Granbull",
    "Grapploct",
    "Graveler",
    "Great Tusk",
    "Greavard",
    "Greedent",
    "Greninja",
    "Greninja-Ask",
    "Grimer",
    "Grimmsnarl",
    "Grookey",
    "Grotle",
    "Groudon",
    "Grovyle",
    "Growlithe",
    "Grubbin",
    "Grumpig",
    "Gulpin",
    "Gumshoos",
    "Gurdurr",
    "Guzzlord",
    "Gyarados",
    "Hakamo-o",
    "Happiny",
    "Hariyama",
    "Hatenna",
    "Hatterene",
    "Hattrem",
    "Haunter",
    "Hawlucha",
    "Haxorus",
    "Heatmor",
    "Heatran",
    "Heliolisk",
    "Helioptile",
    "Heracross",
    "Herdier",
    "Hippopotas",
    "Hippowdon",
    "Hitmonchan",
    "Hitmonlee",
    "Hitmontop",
    "Ho-oh",
    "Honchkrow",
    "Honedge",
    "Hoopa",
    "Hoothoot",
    "Hoppip",
    "Horsea",
    "Houndoom",
    "Houndour",
    "Houndstone",
    "Huntail",
    "Hydreigon",
    "Hypno",
    "Igglybuff",
    "Illumise",
    "Impidimp",
    "Incineroar",
    "Indeedee",
    "Infernape",
    "Inkay",
    "Inteleon",
    "Iron Bundle",
    "Iron Hands",
    "Iron Jugulis",
    "Iron Moth",
    "Iron Thorns",
    "Iron Treads",
    "Iron Valiant",
    "Ivysaur",
    "Jangmo-o",
    "Jellicent",
    "Jigglypuff",
    "Jirachi",
    "Jolteon",
    "Joltik",
    "Jumpluff",
    "Jynx",
    "Kabuto",
    "Kabutops",
    "Kadabra",
    "Kakuna",
    "Kangaskhan",
    "Karrablast",
    "Kartana",
    "Kecleon",
    "Keldeo",
    "Kilowattrel",
    "Kingambit",
    "Kingdra",
    "Kingler",
    "Kirlia",
    "Klang",
    "Klawf",
    "Kleavor",
    "Kleavor",
    "Klefki",
    "Klink",
    "Klinklang",
    "Koffing",
    "Komala",
    "Kommo-o",
    "Koraidon",
    "Krabby",
    "Kricketot",
    "Kricketune",
    "Krokorok",
    "Krookodile",
    "Kubfu",
    "Kyogre",
    "Kyurem",
    "Lairon",
    "Lampent",
    "Landorus",
    "Lanturn",
    "Lapras",
    "Larvesta",
    "Larvitar",
    "Latias",
    "Latios",
    "Leafeon",
    "Leavanny",
    "Lechonk",
    "Ledian",
    "Ledyba",
    "Lickilicky",
    "Lickitung",
    "Liepard",
    "Lileep",
    "Lilligant",
    "Lillipup",
    "Linoone",
    "Litleo",
    "Litten",
    "Litwick",
    "Lokix",
    "Lombre",
    "Lopunny",
    "Lotad",
    "Loudred",
    "Lucario",
    "Ludicolo",
    "Lugia",
    "Lumineon",
    "Lunala",
    "Lunala",
    "Lunatone",
    "Lurantis",
    "Luvdisc",
    "Luxio",
    "Luxray",
    "Lycanroc",
    "Mabosstiff",
    "Machamp",
    "Machoke",
    "Machop",
    "Magby",
    "Magcargo",
    "Magearna",
    "Magikarp",
    "Magmar",
    "Magmortar",
    "Magnemite",
    "Magneton",
    "Magnezone",
    "Makuhita",
    "Malamar",
    "Mamoswine",
    "Manaphy",
    "Mandibuzz",
    "Manectric",
    "Mankey",
    "Mantine",
    "Mantyke",
    "Maractus",
    "Mareanie",
    "Mareep",
    "Marill",
    "Marowak",
    "Marshadow",
    "Marshtomp",
    "Maschiff",
    "Masquerain",
    "Maushold",
    "Mawile",
    "Medicham",
    "Meditite",
    "Meganium",
    "Melmetal",
    "Melmetal",
    "Meloetta",
    "Meltan",
    "Meowscarada",
    "Meowstic",
    "Meowth",
    "Mesprit",
    "Metagross",
    "Metang",
    "Metapod",
    "Mew",
    "Mewtwo",
    "Mienfoo",
    "Mienshao",
    "Mightyena",
    "Milcery",
    "Milotic",
    "Miltank",
    "MimeJr",
    "Mimikyu",
    "Minccino",
    "Minior",
    "Minun",
    "Miraidon",
    "Misdreavus",
    "Mismagius",
    "Moltres",
    "Monferno",
    "Morelull",
    "Morgrem",
    "Morpeko",
    "Mothim",
    "Mr. Mime",
    "Mr. Rime",
    "Mudbray",
    "Mudkip",
    "Mudsdale",
    "Muk",
    "Munchlax",
    "Munna",
    "Murkrow",
    "Musharna",
    "Nacli",
    "Naclstack",
    "Naganadel",
    "Natu",
    "Necrozma",
    "Necrozma",
    "Nickit",
    "Nidoking",
    "Nidoqueen",
    "Nidoran_F",
    "Nidoran_M",
    "Nidorina",
    "Nidorino",
    "Nihilego",
    "Nincada",
    "Ninetales",
    "Ninjask",
    "Noctowl",
    "Noibat",
    "Noivern",
    "Nosepass",
    "Numel",
    "Nuzleaf",
    "Nymble",
    "Obstagoon",
    "Octillery",
    "Oddish",
    "Oinkologne",
    "Omanyte",
    "Omastar",
    "Onix",
    "Oranguru",
    "Orbeetle",
    "Oricorio",
    "Orthworm",
    "Oshawott",
    "Overqwil",
    "Pachirisu",
    "Palafin",
    "Palkia",
    "Palossand",
    "Palpitoad",
    "Pancham",
    "Pangoro",
    "Panpour",
    "Pansage",
    "Pansear",
    "Paras",
    "Parasect",
    "PartnerEevee",
    "PartnerPikachu",
    "Passimian",
    "Patrat",
    "Pawmi",
    "Pawmo",
    "Pawmot",
    "Pawniard",
    "Pecharunt",
    "Pelipper",
    "Perrserker",
    "Persian",
    "Petilil",
    "Phanpy",
    "Phantump",
    "Pheromosa",
    "Phione",
    "Pichu",
    "Pidgeot",
    "Pidgeotto",
    "Pidgey",
    "Pidove",
    "Pignite",
    "Pikachu",
    "PikachuSurfing",
    "Pikipek",
    "Piloswine",
    "Pincurchin",
    "Pineco",
    "Pinsir",
    "Piplup",
    "Plusle",
    "Poipole",
    "Politoed",
    "Poliwag",
    "Poliwhirl",
    "Poliwrath",
    "Polteageist",
    "Ponyta",
    "Poochyena",
    "Popplio",
    "Porygon",
    "Porygon2",
    "PorygonZ",
    "Primarina",
    "Primeape",
    "Prinplup",
    "Probopass",
    "Psyduck",
    "Pumpkaboo",
    "Pupitar",
    "Purrloin",
    "Purugly",
    "Pyroar",
    "Pyukumuku",
    "Quagsire",
    "Quaquaval",
    "Quaxly",
    "Quaxwell",
    "Quilava",
    "Quilladin",
    "Qwilfish",
    "Raboot",
    "Rabsca",
    "Raichu",
    "Raikou",
    "Ralts",
    "Rampardos",
    "Rapidash",
    "Raticate",
    "Rattata",
    "Rayquaza",
    "Regice",
    "Regidrago",
    "Regieleki",
    "Regigigas",
    "Regirock",
    "Registeel",
    "Relicanth",
    "Rellor",
    "Remoraid",
    "Reshiram",
    "Reuniclus",
    "Revavroom",
    "Rhydon",
    "Rhyhorn",
    "Rhyperior",
    "Ribombee",
    "Rillaboom",
    "Riolu",
    "Roaring Moon",
    "Rockruff",
    "Rockruff",
    "Roggenrola",
    "Rolycoly",
    "Rookidee",
    "Roselia",
    "Roserade",
    "Rotom",
    "Rowlet",
    "Rufflet",
    "Runerigus",
    "Sableye",
    "Salamence",
    "Salandit",
    "Salazzle",
    "Samurott",
    "Sandaconda",
    "Sandile",
    "Sandshrew",
    "Sandslash",
    "Sandy Shocks",
    "Sandygast",
    "Sawk",
    "Sawsbuck",
    "Scatterbug",
    "Sceptile",
    "Scizor",
    "Scolipede",
    "Scorbunny",
    "Scovillain",
    "Scrafty",
    "Scraggy",
    "Scream Tail",
    "Scyther",
    "Seadra",
    "Seaking",
    "Sealeo",
    "Seedot",
    "Seel",
    "Seismitoad",
    "Sentret",
    "Serperior",
    "Servine",
    "Seviper",
    "Sewaddle",
    "Sharpedo",
    "Shaymin",
    "Shaymin-sky",
    "Shedinja",
    "Shelgon",
    "Shellder",
    "Shellos",
    "Shelmet",
    "Shieldon",
    "Shiftry",
    "Shiinotic",
    "Shinx",
    "Shroodle",
    "Shroomish",
    "Shuckle",
    "Shuppet",
    "Sigilyph",
    "Silcoon",
    "Silicobra",
    "Silvally",
    "Simipour",
    "Simisage",
    "Simisear",
    "Sinistea",
    "Sirfetch'd",
    "Sizzlipede",
    "Skarmory",
    "Skeledirge",
    "Skiddo",
    "Skiploom",
    "Skitty",
    "Skorupi",
    "Skrelp",
    "Skuntank",
    "Skwovet",
    "Slaking",
    "Slakoth",
    "Sliggoo",
    "Slither Wing",
    "Slowbro",
    "Slowking",
    "Slowpoke",
    "Slugma",
    "Slurpuff",
    "Smeargle",
    "Smoliv",
    "Smoochum",
    "Sneasel",
    "Sneasler",
    "Snivy",
    "Snom",
    "Snorlax",
    "Snorunt",
    "Snover",
    "Snubbull",
    "Sobble",
    "Solgaleo",
    "Solosis",
    "Solrock",
    "Spearow",
    "Spectrier",
    "Spewpa",
    "Spheal",
    "Spidops",
    "Spinarak",
    "Spinda",
    "Spiritomb",
    "Spoink",
    "Sprigatito",
    "Spritzee",
    "Squawkabilly",
    "Squirtle",
    "Stakataka",
    "Stantler",
    "Staraptor",
    "Staravia",
    "Starly",
    "Starmie",
    "Staryu",
    "Steelix",
    "Steenee",
    "Stonjourner",
    "Stoutland",
    "Stufful",
    "Stunfisk",
    "Stunky",
    "Sudowoodo",
    "Suicune",
    "Sunflora",
    "Sunkern",
    "Surskit",
    "Swablu",
    "Swadloon",
    "Swalot",
    "Swampert",
    "Swanna",
    "Swellow",
    "Swinub",
    "Swirlix",
    "Swoobat",
    "Sylveon",
    "Tadbulb",
    "Taillow",
    "Talonflame",
    "Tandemaus",
    "Tangela",
    "Tangrowth",
    "Tapu Bulu",
    "Tapu Fini",
    "Tapu Koko",
    "Tapu Lele",
    "Tarountula",
    "Tatsugiri",
    "Tauros",
    "Teddiursa",
    "Tentacool",
    "Tentacruel",
    "Tepig",
    "Terrakion",
    "Thievul",
    "Throh",
    "Thundurus",
    "Thwackey",
    "Timburr",
    "Ting-Lu",
    "Tinkatink",
    "Tinkaton",
    "Tinkatuff",
    "Tirtouga",
    "Toedscool",
    "Toedscruel",
    "Togedemaru",
    "Togekiss",
    "Togepi",
    "Togetic",
    "Torchic",
    "Torkoal",
    "Tornadus",
    "Torracat",
    "Torterra",
    "Totodile",
    "Toucannon",
    "Toxapex",
    "Toxel",
    "Toxicroak",
    "Toxtricity",
    "Tranquill",
    "Trapinch",
    "Treecko",
    "Trevenant",
    "Tropius",
    "Trubbish",
    "Trumbeak",
    "Tsareena",
    "Turtonator",
    "Turtwig",
    "Tympole",
    "Tynamo",
    "Type: Null",
    "Typhlosion",
    "Tyranitar",
    "Tyrantrum",
    "Tyrogue",
    "Tyrunt",
    "Umbreon",
    "Unfezant",
    "Unown",
    "Ursaluna",
    "Ursaring",
    "Urshifu",
    "Uxie",
    "Vanillish",
    "Vanillite",
    "Vanilluxe",
    "Vaporeon",
    "Varoom",
    "Veluza",
    "Venipede",
    "Venomoth",
    "Venonat",
    "Venusaur",
    "Vespiquen",
    "Vibrava",
    "Victini",
    "Victreebel",
    "Vigoroth",
    "Vikavolt",
    "Vileplume",
    "Virizion",
    "Vivillon",
    "Volbeat",
    "Volcanion",
    "Volcarona",
    "Voltorb",
    "Vullaby",
    "Vulpix",
    "Wailmer",
    "Wailord",
    "Walrein",
    "Wartortle",
    "Watchog",
    "Wattrel",
    "Weavile",
    "Weedle",
    "Weepinbell",
    "Weezing",
    "Whimsicott",
    "Whirlipede",
    "Whiscash",
    "Whismur",
    "Wigglytuff",
    "Wiglett",
    "Wimpod",
    "Wingull",
    "Wishiwashi",
    "Wo-Chien",
    "Wobbuffet",
    "Woobat",
    "Wooloo",
    "Wooper",
    "Wormadam",
    "Wugtrio",
    "Wurmple",
    "Wynaut",
    "Wyrdeer",
    "Xatu",
    "Xerneas",
    "Xurkitree",
    "Yamask",
    "Yamper",
    "Yanma",
    "Yanmega",
    "Yungoos",
    "Yveltal",
    "Zacian",
    "Zamazenta",
    "Zangoose",
    "Zapdos",
    "Zarude",
    "Zebstrika",
    "Zekrom",
    "Zeraora",
    "Zigzagoon",
    "Zoroark",
    "Zorua",
    "Zubat",
    "Zweilous",
    "Zygarde",
    "Alolan Marowak",
];

/**
 * Extracts the base species name from a Pokemon name that may include a form.
 * Examples:
 * - "Deoxys-Attack" -> "Deoxys"
 * - "Deoxys-Defense" -> "Deoxys"
 * - "Alolan Marowak" -> "Marowak"
 * - "Greninja-Ask" -> "Greninja"
 * - "Pikachu" -> "Pikachu" (no form)
 */
export function getBaseSpeciesName(pokemonName: string): string {
    // Handle dash-separated forms (e.g., "Deoxys-Attack", "Greninja-Ask")
    const dashIndex = pokemonName.indexOf('-');
    if (dashIndex !== -1) {
        return pokemonName.substring(0, dashIndex);
    }
    
    // Handle space-separated forms (e.g., "Alolan Marowak", "Paldean Tauros (Combat Breed)")
    // Common regional prefixes: Alolan, Galarian, Hisuian, Paldean
    const regionalPrefixes = ['Alolan', 'Galarian', 'Hisuian', 'Paldean'];
    for (const prefix of regionalPrefixes) {
        if (pokemonName.startsWith(prefix + ' ')) {
            const afterPrefix = pokemonName.substring(prefix.length + 1);
            // For Paldean Tauros breeds, extract just "Tauros" (remove breed in parentheses)
            if (afterPrefix.startsWith('Tauros (')) {
                return 'Tauros';
            }
            // For other regional forms, return the base name
            return afterPrefix;
        }
    }
    
    // No form detected, return as-is
    return pokemonName;
}

/**
 * Converts a form name to match the file naming convention used for Pokemon images.
 * Most forms use lowercase, but some special cases use capitalized or mixed case.
 * Examples:
 * - "Origin" -> "origin"
 * - "Incarnate" -> "incarnate"
 * - "Normal" -> "Normal" (stays capitalized for Deoxys)
 * - "East" -> "East" (stays capitalized for Shellos/Gastrodon)
 * - "Amped" -> "Amped" (stays capitalized for Toxtricity)
 * - "Dusk Mane" -> "dusk-mane" (spaces become dashes, lowercase)
 * - "10%" -> "10%" (special characters preserved, lowercase)
 */
export function getFormNameForFile(formName: string): string {
    // Forms that should stay capitalized (matching existing file names)
    const capitalizedForms = [
        'Normal', 'Attack', 'Defense', 'Speed',  // Deoxys
        'East', 'West',  // Shellos, Gastrodon
        'Amped',  // Toxtricity
    ];
    
    // Check if this form should stay capitalized
    if (capitalizedForms.includes(formName)) {
        return formName;
    }
    
    // For "Low Key", convert to lowercase with dash
    if (formName === 'Low Key') {
        return 'low-key';
    }
    
    // Convert spaces to dashes and lowercase everything else
    // Special characters like "%" will be preserved
    return formName
        .replace(/\s+/g, '-')  // Replace spaces with dashes
        .toLowerCase();
}

/**
 * Alternative move type suffixes used to distinguish Pokemon with alternative moves
 */
export const ALTERNATIVE_MOVE_SUFFIXES = ['-egg-moves', '-event-pokemon', '-cross-generation'] as const;

export type AlternativeMoveType = 'egg-moves' | 'event-pokemon' | 'cross-generation';

/**
 * Extracts the alternative move type from a Pokemon name if present.
 * Returns the type or null if not found.
 * Examples:
 * - "Blastoise-egg-moves" -> "egg-moves"
 * - "Pikachu-event-pokemon" -> "event-pokemon"
 * - "Blastoise" -> null
 */
export function getAlternativeMoveType(pokemonName: string): AlternativeMoveType | null {
    for (const suffix of ALTERNATIVE_MOVE_SUFFIXES) {
        if (pokemonName.endsWith(suffix)) {
            return suffix.substring(1) as AlternativeMoveType; // Remove leading dash
        }
    }
    return null;
}

/**
 * Checks if a Pokemon name has an alternative move type suffix.
 */
export function hasAlternativeMoveType(pokemonName: string): boolean {
    return getAlternativeMoveType(pokemonName) !== null;
}

/**
 * Appends an alternative move type suffix to a Pokemon name.
 * If the type is null or undefined, returns the name unchanged.
 */
export function appendAlternativeMoveType(pokemonName: string, type: AlternativeMoveType | null | undefined): string {
    if (!type) return pokemonName;
    return `${pokemonName}-${type}`;
}

/**
 * Removes the alternative move type suffix from a Pokemon name if present.
 * Returns the base Pokemon name.
 */
export function removeAlternativeMoveType(pokemonName: string): string {
    const altType = getAlternativeMoveType(pokemonName);
    if (!altType) return pokemonName;
    return pokemonName.substring(0, pokemonName.length - altType.length - 1); // -1 for the dash
}