/**
 * Copies the Solodex pokedex dataset into public/data/pokedex/, one classic script per game.
 *
 *   npm run sync-pokedex                      # reads ../solodex/data_objects-main
 *   npm run sync-pokedex -- <path to data_objects-main>
 *
 * Mirrors how Solodex itself assembles its data (src/renderer/src/data/index.ts): Gen 1-4
 * games come from the sections of pokedex.js, everything later from the per-game files in
 * pokedex/. The text is copied verbatim — only the `export const ...` header is replaced by
 * an assignment into window.pokedexData, so the app can load a file with a plain <script>
 * tag (module imports and fetch() are unavailable on Electron's file:// pages).
 *
 * Which key maps to which file is POKEDEX_FILES in src/utils/pokemon/pokedex.ts.
 */
import * as fs from 'fs'
import * as path from 'path'
import { fileURLToPath } from 'url'

const ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..') + path.sep
const OUT_DIR = ROOT + 'public/data/pokedex/'

const { POKEDEX_FILES } = await import('../src/utils/pokemon/pokedex.ts')

const sourceDir = path.resolve(process.argv[2] ?? path.join(ROOT, '..', 'solodex', 'data_objects-main')) + path.sep
if (!fs.existsSync(sourceDir + 'pokedex.js')) {
  console.error(`No pokedex.js under ${sourceDir} — pass the path to Solodex's data_objects-main.`)
  process.exit(1)
}

/** Keys whose data lives as a section of the combined pokedex.js rather than a per-game file. */
const COMBINED_SECTIONS = new Set([
  'Red and Blue', 'Yellow', 'Gold and Silver', 'Crystal', 'Ruby and Sapphire', 'Emerald',
  'FireRed and LeafGreen', 'Diamond and Pearl', 'Platinum', 'HeartGold and SoulSilver',
])

/**
 * Splits pokedex.js into its top-level sections by text. Sections open with `    "Name": {`
 * at four spaces of indentation and close with `    }` or `    },` at the same depth; the
 * body is de-indented by those four spaces so it matches the per-game files.
 */
function splitCombined(text: string): Map<string, string> {
  const lines = text.split(/\r?\n/)
  const sections = new Map<string, string>()
  let current: string | null = null
  let body: string[] = []
  for (const line of lines) {
    const open = current === null && /^ {4}"([^"]+)": \{$/.exec(line)
    if (open) { current = open[1]; body = ['{']; continue }
    if (current !== null) {
      if (line === '    }' || line === '    },') {
        body.push('}')
        sections.set(current, body.join('\n'))
        current = null
      } else {
        body.push(line.startsWith('    ') ? line.substring(4) : line)
      }
    }
  }
  return sections
}

/** Strips the `export const <name> = ` header and any trailing semicolon/whitespace. */
function stripModuleHeader(text: string, file: string): string {
  const m = /^\s*export const \w+ = /.exec(text)
  if (!m) throw new Error(`${file}: expected "export const <name> = " at the top`)
  return text.substring(m[0].length).replace(/;?\s*$/, '')
}

/** Evaluates a generated file the way the verify script does, returning the section it registered. */
function evalGenerated(file: string, key: string): Record<string, unknown> {
  const g = globalThis as any
  g.window = g
  g.pokedexData = undefined
  ;(0, eval)(fs.readFileSync(file, 'utf8'))
  const section = g.pokedexData?.[key]
  if (!section || typeof section !== 'object') throw new Error(`${file}: did not register pokedexData[${JSON.stringify(key)}]`)
  return section
}

fs.mkdirSync(OUT_DIR, { recursive: true })
const combined = splitCombined(fs.readFileSync(sourceDir + 'pokedex.js', 'utf8'))

const summary: string[] = []
for (const [key, file] of Object.entries(POKEDEX_FILES)) {
  let body: string
  let origin: string
  if (COMBINED_SECTIONS.has(key)) {
    const section = combined.get(key)
    if (!section) throw new Error(`pokedex.js has no "${key}" section`)
    body = section
    origin = `pokedex.js ["${key}"]`
  } else {
    const src = sourceDir + 'pokedex/' + file + '.js'
    if (!fs.existsSync(src)) throw new Error(`missing ${src}`)
    body = stripModuleHeader(fs.readFileSync(src, 'utf8'), src)
    origin = `pokedex/${file}.js`
  }
  const out = OUT_DIR + file + '.js'
  const header =
    `// Generated by scripts/sync-pokedex-data.ts from Solodex ${origin} — do not edit, run \`npm run sync-pokedex\`.\n` +
    `window.pokedexData = window.pokedexData || {};\n` +
    `window.pokedexData[${JSON.stringify(key)}] = `
  fs.writeFileSync(out, header + body + ';\n')
  const entries = Object.keys(evalGenerated(out, key)).length
  summary.push(`${key.padEnd(36)} <- ${origin.padEnd(40)} ${entries} entries  ${(fs.statSync(out).size / 1024 / 1024).toFixed(1)} MB`)
}

// Anything in the output dir that POKEDEX_FILES no longer names is stale.
const expected = new Set(Object.values(POKEDEX_FILES).map(f => f + '.js'))
for (const f of fs.readdirSync(OUT_DIR)) {
  if (f.endsWith('.js') && !expected.has(f)) {
    fs.unlinkSync(OUT_DIR + f)
    summary.push(`removed stale ${f}`)
  }
}

console.log(summary.join('\n'))
console.log(`\nSource: ${sourceDir}\nOutput: ${OUT_DIR}`)
